apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-ex-v06n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-ex-v06n
    app.kubernetes.io/part-of: python-ex
  name: python-ex-v06n
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-ex-v06n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-ex-v06n
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/eyuen-tenant/python-ex/python-ex-v06n@sha256:39bc4f111a476f41793c2f78fb8c6eba80ac36bd4a9d85fa0bab4a2bec6a3061
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
